### ISSUE TITLE
Restaurant Analytics Page

### ISSUE THREAD

**Issue by Henry-Owusu** [Simon-157/fast-foodies#6]
@K0TAA @Henry-Owusu 

Create the user Analytics page

**Comment by urdadx** [comment]
The page should look something like this..

![Screenshot from 2023-02-15 14-18-54](https://user-images.githubusercontent.com/70736338/219055366-b3d7bc61-6c21-4510-b1ce-1a34adf78b87.png)

**Comment by Henry-Owusu** [comment]
Completed
